expname: castle

data:
  data_dir: ../Data/castle/images

  #=========
  N_rays: 1024
  #=========

model:
  framework: NeRF
  net_w: 128

  use_fine_model: true
  net_d_fine: 8
  net_w_fine: 128
  net_skips_fine: [4] 

training:
  lr_nerf: 5.0e-4
  num_epoch_pre: 1000 # number of epochs run before refinement
  num_epoch: 5000